CREATE TABLE IF NOT EXISTS users  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    email varchar(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS categories  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat DECIMAL NOT NULL,
    lon DECIMAL NOT NULL
);

CREATE TABLE IF NOT EXISTS events  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation varchar(200) NOT NULL,
    category_id INTEGER references categories(id) NOT Null,
    confirmedRequests INTEGER NOT NUll,
    createdOn TIMESTAMP NOT NULL,
    description varchar(200) NOT NULL,
    eventDate TIMESTAMP NOT NULL,
    initiator_id INTEGER references users(id) NOT NULL,
    location_id INTEGER references locations(id) NOT NULL,
    paid Boolean NOT NULL,
    participantLimit INTEGER NOT NULL,
    publishedOn TIMESTAMP NOT NULL,
    requestModeration Boolean NOT NULL,
    state varchar(20) NOT NULL,
    title varchar(200) NOT NULL,
    views INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned Boolean NOT Null,
    title varchar(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_events  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compilation_id INTEGER references compilations(id) NOT NULL,
    event_id INTEGER references events(id) NOT NULL
);

CREATE TABLE IF NOT EXISTS requests  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP NOT Null,
    event_id INTEGER references events(id) NOT NULL,
    requester_id INTEGER references users(id) NOT NULL,
    status varchar(200) NOT NULL,
    UNIQUE (event_id, requester_id)
);