CREATE TABLE IF NOT EXISTS endpoint_hit  (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app varchar(40) NOT NULL,
    uri varchar(40) NOT NULL,
    ip varchar(40) NOT NULL,
    time_stamp timestamp NOT Null
);